image: node:8.10

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - node
        script:
          - npm install
    - parallel:
        - step:
            name: Jest test and code coverage
            caches:
              - node
            script:
              - TZ="America/Bogota" npm run test:ci
        - step:
            name: Eslint
            caches:
              - node
            script:
              - npm run lint
  branches:
    master:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install
      - parallel:
          - step:
              name: Jest test and code coverage
              caches:
                - node
              script:
                - TZ="America/Bogota" npm run test:ci
          - step:
              name: Eslint
              caches:
                - node
              script:
                - npm run lint
          - step:
              name: Sync assets to S3
              caches:
                - node
              script:
                - apt-get update && apt-get install -y python-dev
                - curl -O https://bootstrap.pypa.io/get-pip.py
                - python get-pip.py
                - pip install awscli
                - npm run sync:assets
      - step:
          name: Deploy to production
          caches:
            - node
          deployment: production
          script:
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
            - pip install aws-sam-cli
            - npm run deploy
