version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Linter
          command: npm run lint -- --format junit -o coverage/junit/js-lint-results.xml
      - run:
          name: Test suite
          command: npm run test:coverage -- --ci
          environment:
            TZ: 'America/Bogota'
            JEST_JUNIT_OUTPUT: 'coverage/junit/js-test-results.xml'
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage/junit
      - run: npx codecov
  deploy:
    docker:
      - image: circleci/python:3.6.8-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install awscli - aws-sam-cli
          command: sudo pip install --upgrade awscli aws-sam-cli
      - run: npm run sync:assets
      - run: npm run deploy

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
