version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.10
        environment:
          TZ: 'America/Bogota'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: 'Run Jest and Collect Coverage Reports'
          command: npm run test
      - store_artifacts:
          path: coverage
      - run:
          command: npx codecov
  deploy:
    docker:
      - image: circleci/node:8.10
        environment:
          - AWS_DEFAULT_REGION=us-east-1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install awscli aws-sam-cli
          command: |
            sudo apt-get install python3 python3-pip -y
            sudo pip3 install awscli --upgrade
      - run: npm run sync:assets
      - run: npm run deploy

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
